In [2]:
from sklearn.datasets import load_iris
from sklearn.ensemble import RandomForestClassifier
import pandas as pd
import numpy as np
np.random.seed(0)

In [3]:
iris=load_iris()
df=pd.DataFrame(iris.data,columns=iris.feature_names)
df.head()


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

df['species']=pd.Categorical_fro

In [21]:
df['species']=pd.Categorical.from_codes(iris.target,iris.target_names)
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

  species  
0  setosa  
1  setosa  
2  setosa  
3  setosa  
4  setosa

In [26]:
df['is_train']=np.random.uniform(0,1,len(df))<=0.75
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

  species  is_train  
0  setosa      True  
1  setosa      True  
2  setosa      True  
3  setosa      True  
4  setosa      True

In [30]:
# creating the dataset in train and test data
train,test=df[df['is_train']==True],df[df['is_train']==False]
print("the data is train data",len(train))
print('the data is test data',len(test))

the data is train data 119
the data is test data 31


In [32]:
# creating the feature for understanding the data
features=df.columns[:4]
features

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)'],
      dtype='object')

In [40]:
y=pd.factorize(train['species'])[0]
y


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [39]:
using the decison Tree classifier


CategoricalIndex(['setosa', 'versicolor', 'virginica'], categories=['setosa', 'versicolor', 'virginica'], ordered=False, dtype='category')

In [42]:
rfs=RandomForestClassifier(n_jobs=4,random_state=0)
rfs.fit(train[features],y)

RandomForestClassifier(n_jobs=4, random_state=0)

In [43]:
# applying the model to predict the model
rfs.predict(test[features])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1,
       2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [45]:
# viewing the predicted probability using proba
rfs.predict_proba(test[features])[10:20]

array([[1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [0.  , 0.94, 0.06],
       [0.  , 0.96, 0.04],
       [0.  , 1.  , 0.  ],
       [0.  , 0.99, 0.01],
       [0.  , 1.  , 0.  ],
       [0.  , 0.99, 0.01],
       [0.  , 1.  , 0.  ],
       [0.01, 0.  , 0.99]])

In [46]:
# mapping names for the plants using the test cases we have predicted
preds=iris.target_names[rfs.predict(test[features])]

In [48]:
preds[:5]


array(['setosa', 'setosa', 'setosa', 'setosa', 'setosa'], dtype='<U10')

In [52]:
# creating a confusion matrix 
pd.crosstab(test['species'],preds,rownames=['actual_species'],colnames=['predicted_species'])

predicted_species  setosa  versicolor  virginica
actual_species                                  
setosa                 12           0          0
versicolor              0           7          0
virginica               0           1         11

In [56]:
# we can check whether the fruit is what using 

preds=iris.target_names[rfs.predict([[4,1,2,2.5],[4,1.2,2.6,3.4]])]

In [57]:
preds

array(['setosa', 'virginica'], dtype='<U10')